### ISSUE TITLE
# Delegate And protocol structure has to be implemented in the attendance feature [@Edvoid Admin]

### ISSUE THREAD

**Issue by dheerajghub** [project-edvoid/Issue-Tracker#32]
**Problems with current architecture in attendance feature**

Currently, I am accessing the data whether attendance marked or not through checking that cell is clicked or not if clicked then I am changing the images and flag (Which keeps count on a number of students marked) to present or absent. But the problem occurs when the cell is getting out of the view I can't access the cell when they're out of view with ```cellFor(:rowAt)``` method.

**Solution To Above Problem is**

I have to use ```delegates and protocols``` to retrieve the data from cell class to controller And maybe there an efficient way to do that.

**Comment by rohitcoder** [comment]
Fixed?????
